version: "3"
services:
  nginx-container:
    build:
      context: ./nginx
    ports:
      - "8081:80"
    restart: on-failure

  apache-container:
    build:
      context: ./apache
    ports:
      - "8082:80"
    restart: on-failure
